language: go
sudo: false

go:
 - 1.8.x
 - master

branches:
  only:
  - master

before_install:
  - apt update -q
  - apt install git -y

install:
  - go get github.com/die-net/lrucache
  - go get github.com/gorilla/mux
  - go get github.com/joho/godotenv
  - go get github.com/go-sql-driver/mysql

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - git clone https://github.com/xenu256/qprob_goapi
    - cd qprob_goapi/api_server
    - go build