language: go
sudo: false

go:
 - 1.8.x
 - master

branches:
  only:
  - master

install:
  - #

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - go get -t -v ./...
    - go build ./api_server
