sudo: false

go:
 - 1.8

branches:
  only:
  - master

install:
  - go get ./api_server
  - go get github.com/go-sql-driver/mysql
  - go getpackage github.com/gorilla/mux
  - go getpackage github.com/joho/godotenv

notifications:
  email:
    on_success: never
    on_failure: always

script:
    - go build ./api_server
